// <auto-generated> Run: pwsh tools/glossary/Invoke-AbortReasonCodegen.ps1
namespace ProjectAegis.Sim.Glossary;

/// <summary>Stable order-log codes from data/glossary/abort_reason_manifest.json (req 12).</summary>
public static partial class AbortReasonCatalog
{
    public static class Doctrine
    {
        public const string ROE_HOLD_FIRE = "ROE_HOLD_FIRE";
        public const string ROE_WEAPONS_TIGHT = "ROE_WEAPONS_TIGHT";
        public const string WRA_RANGE = "WRA_RANGE";
        public const string WRA_SALVO = "WRA_SALVO";
        public const string EMCON_OFF = "EMCON_OFF";
        public const string NO_FIRE_CONTROL_TRACK = "NO_FIRE_CONTROL_TRACK";
        public const string COMMS_DENIED = "COMMS_DENIED";
    }

    public static class Engage
    {
        public const string OUT_OF_ENVELOPE = "OUT_OF_ENVELOPE";
        public const string DLZ_OUT = "DLZ_OUT";
        public const string NO_AMMO = "NO_AMMO";
        public const string NO_FIRE_CONTROL_TRACK = "NO_FIRE_CONTROL_TRACK";
        public const string EMCON_OFF = "EMCON_OFF";
        public const string ROE_HOLD_FIRE = "ROE_HOLD_FIRE";
        public const string ROE_WEAPONS_TIGHT = "ROE_WEAPONS_TIGHT";
        public const string TARGET_DESTROYED = "TARGET_DESTROYED";
        public const string WRA_SALVO = "WRA_SALVO";
        public const string BLACK_PROJECT_REQUIRED = "BLACK_PROJECT_REQUIRED";
        public const string TECHNOLOGY_LEVEL_EXCEEDED = "TECHNOLOGY_LEVEL_EXCEEDED";
    }

    public static class Logistics
    {
        public const string STRIKE_UNREACHABLE = "STRIKE_UNREACHABLE";
        public const string STRIKE_UNREACHABLE_FUEL = "STRIKE_UNREACHABLE_FUEL";
    }

}

