// <auto-generated> Run: pwsh tools/glossary/Invoke-AbortReasonCodegen.ps1
namespace ProjectAegis.Sim.Glossary;

/// <summary>Stable order-log codes from data/glossary/abort_reason_manifest.json (req 12).</summary>
public static partial class AbortReasonCatalog
{
    public static class Doctrine
    {
        public const string ROE_HOLD_FIRE = "ROE_HOLD_FIRE";
        public const string ROE_WEAPONS_TIGHT = "ROE_WEAPONS_TIGHT";
        public const string WRA_RANGE = "WRA_RANGE";
        public const string WRA_SALVO = "WRA_SALVO";
        public const string EMCON_OFF = "EMCON_OFF";
        public const string NO_FIRE_CONTROL_TRACK = "NO_FIRE_CONTROL_TRACK";
        public const string COMMS_DENIED = "COMMS_DENIED";
    }

    public static class Engage
    {
        public const string OUT_OF_ENVELOPE = "OUT_OF_ENVELOPE";
        public const string DLZ_OUT = "DLZ_OUT";
        public const string NO_AMMO = "NO_AMMO";
        public const string NO_FIRE_CONTROL_TRACK = "NO_FIRE_CONTROL_TRACK";
        public const string EMCON_OFF = "EMCON_OFF";
        public const string ROE_HOLD_FIRE = "ROE_HOLD_FIRE";
        public const string ROE_WEAPONS_TIGHT = "ROE_WEAPONS_TIGHT";
        public const string TARGET_DESTROYED = "TARGET_DESTROYED";
        public const string WRA_SALVO = "WRA_SALVO";
        public const string BLACK_PROJECT_REQUIRED = "BLACK_PROJECT_REQUIRED";
        public const string TECHNOLOGY_LEVEL_EXCEEDED = "TECHNOLOGY_LEVEL_EXCEEDED";
        public const string MOUNT_OFFLINE = "MOUNT_OFFLINE";
        public const string DOMAIN_NO_SOLUTION = "DOMAIN_NO_SOLUTION";
        public const string AIR_NOT_READY = "AIR_NOT_READY";
    }

    public static class Logistics
    {
        public const string STRIKE_UNREACHABLE = "STRIKE_UNREACHABLE";
        public const string STRIKE_UNREACHABLE_FUEL = "STRIKE_UNREACHABLE_FUEL";
        public const string AIR_NOT_READY = "AIR_NOT_READY";
        public const string FERRY_UNREACHABLE = "FERRY_UNREACHABLE";
        public const string FERRY_UNREACHABLE_FUEL = "FERRY_UNREACHABLE_FUEL";
    }

    public static class Sensor
    {
        public const string SENSOR_OFFLINE = "SENSOR_OFFLINE";
        public const string SENSOR_EMCON_BLOCKED = "SENSOR_EMCON_BLOCKED";
        public const string DATALINK_STALE = "DATALINK_STALE";
        public const string TRACK_STALE = "TRACK_STALE";
    }

    public static class Cyber
    {
        public const string CYBER_LINK_DEGRADED = "CYBER_LINK_DEGRADED";
        public const string CYBER_LINK_DOWN = "CYBER_LINK_DOWN";
        public const string CYBER_ORDER_DELAY = "CYBER_ORDER_DELAY";
        public const string CYBER_SPOOF_TRACK = "CYBER_SPOOF_TRACK";
    }

}

