# Generates AbortReasonCatalog.Generated.cs from data/glossary/abort_reason_manifest.json
param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
)

$ErrorActionPreference = 'Stop'
$manifestPath = Join-Path $RepoRoot 'data/glossary/abort_reason_manifest.json'
$outPath = Join-Path $RepoRoot 'src/ProjectAegis.Sim/Glossary/AbortReasonCatalog.Generated.cs'

if (-not (Test-Path $manifestPath)) {
    throw "Manifest not found: $manifestPath"
}

$manifest = Get-Content $manifestPath -Raw | ConvertFrom-Json
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated> Run: pwsh tools/glossary/Invoke-AbortReasonCodegen.ps1')
[void]$sb.AppendLine('namespace ProjectAegis.Sim.Glossary;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>Stable order-log codes from data/glossary/abort_reason_manifest.json (req 12).</summary>')
[void]$sb.AppendLine('public static partial class AbortReasonCatalog')
[void]$sb.AppendLine('{')

foreach ($family in $manifest.families) {
    $familyName = $family.name
    [void]$sb.AppendLine("    public static class $familyName")
    [void]$sb.AppendLine('    {')

    if ($family.entries) {
        foreach ($entry in $family.entries) {
            $constName = ($entry.logCode -replace '[^A-Za-z0-9_]', '_')
            [void]$sb.AppendLine("        public const string $constName = `"$($entry.logCode)`";")
        }
    }

    if ($family.stringCodes) {
        foreach ($code in $family.stringCodes) {
            $constName = ($code -replace '[^A-Za-z0-9_]', '_')
            [void]$sb.AppendLine("        public const string $constName = `"$code`";")
        }
    }

    [void]$sb.AppendLine('    }')
    [void]$sb.AppendLine()
}

[void]$sb.AppendLine('}')

$dir = Split-Path $outPath -Parent
if (-not (Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

Set-Content -Path $outPath -Value $sb.ToString() -Encoding utf8NoBOM
Write-Host "Wrote $outPath"