name: .NET CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: dotnet-ci-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    uses: ./.github/workflows/dotnet-reusable.yml